<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/7
 * Time: 15:14
 */
namespace Minng\LaravelLang;

use Illuminate\Translation\TranslationServiceProvider as LaravelTranslationServiceProvider;
use Minng\LaravelLang\Commands\Publish as PublishCommand;

class TranslationServiceProvider extends LaravelTranslationServiceProvider
{
    /**
     * Register the service provider
     */
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub

        $this->registerCommands();
    }

    /**
     * Register lang:publish command
     */
    protected function registerCommands()
    {
        $this->commands(PublishCommand::class);
    }

    /**
     * Get the services provided by the provider
     * @return array
     */
    public function provides()
    {
        return array_merge(parent::provides(),[PublishCommand::class]);
    }
}